export { WIDGET_NAMES, isWidgetName, type WidgetName } from "./names";
export { widgetRegistry } from "./registry";
export { default as BoundarySlider } from "./boundary-slider";
export { default as StateMachine } from "./state-machine";
export { default as DecisionTable } from "./decision-table";
export { default as TriageGrid } from "./triage-grid";
export { default as PartitionPicker } from "./partition-picker";
export type { WidgetProps } from "./widget-props";
export { AutomationPyramid } from "./automation-pyramid";
export { WebDriverArchitecture } from "./webdriver-architecture";
export { LifecycleVisualizer } from "./lifecycle-visualizer";
export { POMVisualizer } from "./pom-visualizer";
export { SDLCVisualizer } from "./sdlc-visualizer";
export { JiraBoard } from "./jira-board";
export { ExploratoryTimer } from "./exploratory-timer";
export { TestingTypeSorter } from "./testing-type-sorter";
export { default as PairwiseVisualizer } from "./pairwise-visualizer";
